[package]
name = "transmitter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "transmitter"

[dependencies]
tokio = { version = "1", features = ["net", "rt-multi-thread", "macros", "sync", "time", "signal"] }
tokio-util = "0.7.19" 
tokio-tungstenite = { version = "0.30", features = ["rustls-tls-native-roots"] }
rustls = { version = "0.23.43", default-features = false, features = ["ring", "std"] } # Pure rust
futures-util = "0.3.34"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.39.6"
local-ip-address = "0.6.13"